version: 2

models:
  - name: bing_accounts
    columns:
        - name: account_id
          tests:
              - unique
              - not_null
              
  - name: bing_ad_groups
    columns:
        - name: ad_group_id
          tests:
              - unique
              - not_null
              
  - name: bing_ads
    columns:
        - name: ad_id
          tests:
              - unique
              - not_null
              
  - name: bing_campaigns
    columns:
        - name: campaign_id
          tests:
              - unique
              - not_null
              
  - name: bing_keyword_performance
    columns:
        - name: keyword_performance_report_id
          tests:
              - unique
              - not_null